spring:
  data:
    redis:
      host: ${REDIS_HOSTNAME:localhost}
      port: ${REDIS_PORT:6379}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_updates: true
        jdbc:
          lob:
            non_contextual_creation: true
          time_zone: UTC
        default_schema: auth
        hbm2ddl:
          create_namespaces: true

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOSTNAME:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME:store_builder}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  mail:
    host: ${SMTP_HOSTNAME}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      from: ${SMTP_FROM}
      mail:
        smtp:
          auth: ${SMTP_AUTH:true}
          starttls:
            enable: ${SMTP_STARTTLS:true}

jwt:
  secret: ${SECRET_KEY:jfitbksigtA214dfesdfr86f2OPwb271}  # Минимум 256 бит (32 символа)
  otp:
    expiration: 300 # 5 минут
  access:
    expiration: 900  # 15 минут
  refresh:
    expiration: 604800  # 7 дней

server:
  port: 8081

springdoc:
  server-url: ${GATEWAY_URL:http://localhost:8080/auth}
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    operations-sorter: method
    tags-sorter: alpha
    default-model-expand-depth: 3
    persistAuthorization: true
  api-docs:
    path: /v3/api-docs