apiVersion: apps/v1
kind: Deployment
metadata: { name: catalog , namespace: store-builder }
spec:
  replicas: 2
  selector: { matchLabels: { app: catalog } }
  template:
    metadata: { labels: { app: catalog } }
    spec:
      containers:
        - name: catalog
          image: catalog-service:1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: POSTGRES_HOSTNAME
              value: "db"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: store-builder-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: store-builder-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: store-builder-secrets
                  key: POSTGRES_PASSWORD
            - name: GATEWAY_URL
              value: "http://gateway:8080/catalogs"