apiVersion: v1
kind: Secret
metadata:
  name: store-builder-secrets
  namespace: store-builder
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  SECRET_KEY: "jfitbksigtA321dfesdfr86f2OPwb271"